source "https://rubygems.org"
ruby "3.2.2"
gem "jekyll", "~> 4.3.0"
gem "jekyll-feed", "~> 0.17"
gem "jekyll-paginate-v2", "~> 3.0"
gem "jekyll-seo-tag", "~> 2.8"
gem "jekyll-sitemap", "~> 1.4"
gem "webrick", "~> 1.8"